<?php
$db = new mysqli('localhost', 'root', '', 'db');

if($db->connect_errno){
	die('Sorry unable to connect to database at the moment, Please try again later.');
	}
	
$tab = "CREATE TABLE students (   
addnum 		   INT(5)	      	 NOT NULL	AUTO_INCREMENT,
email  		   VARCHAR(255)    	 NOT NULL,
pnumber  	   VARCHAR(20)    	 NOT NULL,
password  	   VARCHAR(255)    	 NOT NULL,
datestarted    DATE              NOT NULL,
last  		   VARCHAR(255)    	 NOT NULL,
first  		   VARCHAR(255)    	 NOT NULL,
other  		   VARCHAR(255)    	 NOT NULL,
homeadd  	   VARCHAR(255)    	 NOT NULL,
postal  	   VARCHAR(255)    	 NOT NULL,
bday  		   DATE		    	 NOT NULL,
bplace  	   VARCHAR(255)    	 NOT NULL,
country  	   VARCHAR(255)    	 NOT NULL,
state  		   VARCHAR(255)    	 NOT NULL,
outside  	   VARCHAR(255)    	 NOT NULL,
marital  	   VARCHAR(255)    	 NOT NULL,
spouse  	   VARCHAR(255)    	 NOT NULL,
wedded  	   VARCHAR(255)    	 NOT NULL,
ages  		   VARCHAR(255)    	 NOT NULL,
engaged  	   VARCHAR(255)    	 NOT NULL,
health  	   VARCHAR(255)    	 NOT NULL,
physique  	   VARCHAR(255)    	 NOT NULL,
sponsor  	   VARCHAR(255)    	 NOT NULL,
school1  	   VARCHAR(255)    	 NOT NULL,
from1  		   DATE		    	 NOT NULL,
to1  		   DATE		    	 NOT NULL,
cert1  		   VARCHAR(255)    	 NOT NULL,
grade1  	   VARCHAR(255)    	 NOT NULL,
certdate1  	   DATE		    	 NOT NULL,
school2  	   VARCHAR(255)    	 NOT NULL,
from2  		   DATE		    	 NOT NULL,
to2  		   DATE		    	 NOT NULL,
cert2  		   VARCHAR(255)    	 NOT NULL,
grade2  	   VARCHAR(255)    	 NOT NULL,
certdate2  	   DATE		    	 NOT NULL,
school3  	   VARCHAR(255)    	 NOT NULL,
from3  		   DATE		    	 NOT NULL,
to3  		   DATE		    	 NOT NULL,
cert3  		   VARCHAR(255)    	 NOT NULL,
grade3  	   VARCHAR(255)    	 NOT NULL,
certdate3  	   DATE		    	 NOT NULL,
school4  	   VARCHAR(255)    	 NOT NULL,
from4  		   DATE		    	 NOT NULL,
to4  		   DATE		    	 NOT NULL,
cert4  		   VARCHAR(255)    	 NOT NULL,
grade4  	   VARCHAR(255)    	 NOT NULL,
certdate4  	   DATE		    	 NOT NULL,
school5  	   VARCHAR(255)    	 NOT NULL,
from5  		   DATE		    	 NOT NULL,
to5  		   DATE		    	 NOT NULL,
cert5  		   VARCHAR(255)    	 NOT NULL,
grade5  	   VARCHAR(255)    	 NOT NULL,
certdate5  	   DATE		    	 NOT NULL,
denomination   VARCHAR(255)    	 NOT NULL,
pastor         VARCHAR(255)    	 NOT NULL,
caddress       VARCHAR(255)    	 NOT NULL,
baptised       VARCHAR(255)    	 NOT NULL,
occupation     VARCHAR(255)    	 NOT NULL,
position       VARCHAR(255)    	 NOT NULL,
worked         VARCHAR(255)    	 NOT NULL,
held           VARCHAR(255)    	 NOT NULL,
employer       VARCHAR(255)    	 NOT NULL,
emaddress      VARCHAR(255)    	 NOT NULL,
ref1           VARCHAR(255)    	 NOT NULL,
ref1mobile     VARCHAR(255)    	 NOT NULL,
ref1email      VARCHAR(255)    	 NOT NULL,
ref2           VARCHAR(255)    	 NOT NULL,
ref2mobile     VARCHAR(255)    	 NOT NULL,
ref2email      VARCHAR(255)    	 NOT NULL,
ref3           VARCHAR(255)    	 NOT NULL,
ref3mobile     VARCHAR(255)    	 NOT NULL,
ref3email      VARCHAR(255)    	 NOT NULL,
court          VARCHAR(255)    	 NOT NULL,
convicted      VARCHAR(255)    	 NOT NULL,
discipline     VARCHAR(255)    	 NOT NULL,
cdiscipline    VARCHAR(255)    	 NOT NULL,
why		       VARCHAR(255)    	 NOT NULL,
what           VARCHAR(255)    	 NOT NULL,
christian      VARCHAR(255)    	 NOT NULL,
basis          VARCHAR(255)    	 NOT NULL,
datecompleted  DATE         	 NOT NULL,


PRIMARY KEY(addnum) )";
	
if ($db->query($tab) === TRUE){echo "SUCCESSFULLY, Remember to add auto increment " ;} else {echo $db->error;};


?>